export const LOGIN_USER = "AUTH/LOGIN_USER";
export const LOGOUT_USER = "AUTH/LOGOUT_USER";
export const SIGN_UP_USER = "AUTH/SIGN_UP_USER";
export const USER_LOADING = "AUTH/USER_LOADING";
export const SET_CURRENT_USER = "AUTH/SET_CURRENT_USER";
export const RESET_PASSWORD = "AUTH/RESET_PASSWORD";
export const NEW_PASSWORD = "AUTH/NEW_PASSWORD";
export const EMAIL_CONFIRM = "AUTH/EMAIL_CONFIRM";
